version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    env:
      MYSQL_ROOT_PASSWORD: sobhan.m
      MYSQL_DATABASE: pychatdb
      MYSQL_USER: sobhan
      MYSQL_PASSWORD : sobhanpassword
    ports:
    - "3306:3306"
    volumes:
    - dbdata:/var/lib/mysql
  backend:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    -  db
    command:
      uvicorn main:app --reload
  volumes:
  dbdata: